; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = private.ini

[env:esp32dev]
platform = espressif32@6.6.0 ; older version supports ps4Controller library
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	pablomarquez76/PS4_Controller_Host@^1.1.1
	powerbroker2/SerialTransfer@^3.1.5
	ArduinoJson@^6.19.4
	ESP32-WDT@^1.0.0

board_build.partitions = huge_app.csv

build_flags =
    ; this is the mac address of the device that the ps4 controller thinks it's paired to. the library will emulate that address so you don't have to pair it. or really cant. you cant pair it you have to do it this way lol
    -D PS4_TARGET_MAC=\"48:9d:31:e3:43:82\"
    -D CONTROLLER_LED_COLOR=0,255,0
    -D FW_VERSION=\"1.0.0\"
    -D CONFIG_FILE_PATH=\"/config.json\"
    -D ENABLE_WATCHDOG=1
    -D ENABLE_OTA=1
    -D ENABLE_LOGGING=1

upload_speed = 921600
upload_port = /dev/ttyUSB0  ; Change to your port
upload_flags = -d /dev/ttyUSB0

[env:esp32dev-ota]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps = 
    pablomarquez76/PS4_Controller_Host@^1.1.1
    powerbroker2/SerialTransfer@^3.1.5
    ArduinoJson@^6.19.4

build_flags = 
    -D PS4_TARGET_MAC=\"48:9d:31:e3:43:82\"
    -D CONTROLLER_LED_COLOR=0,255,0
    -D FW_VERSION=\"1.0.0\"
    -D CONFIG_FILE_PATH=\"/config.json\"
    -D ENABLE_WATCHDOG=1
    -D ENABLE_OTA=1
    -D ENABLE_LOGGING=1

upload_speed = 921600
upload_port = /dev/ttyUSB0
upload_flags = -d /dev/ttyUSB0
extra_scripts = pre:scripts/pre_upload.py
